local guildData = {
  ["A Paladin Stole My Bike"] = {
    ["@raveslave00"] = {
      [21] = {
        ["timeLast"] = 0,
        ["last"] = 0,
        ["total"] = 0,
        ["timeFirst"] = 0,
      },
      ["timeJoined"] = 1614310155,
      [22] = {
        ["timeLast"] = 0,
        ["last"] = 0,
        ["total"] = 0,
        ["timeFirst"] = 0,
      },
    },
    ["@jester_the.wanderer"] = {
      [21] = {
        ["timeLast"] = 0,
        ["last"] = 0,
        ["total"] = 0,
        ["timeFirst"] = 0,
      },
      ["timeJoined"] = 1617303406,
      [22] = {
        ["timeLast"] = 0,
        ["last"] = 0,
        ["total"] = 0,
        ["timeFirst"] = 0,
      },
    },
    ["@brunoponcejones"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597633156,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["oldestEvents"] = {
      [2] = 1614306688,
      [1] = 1597626781,
    },
    ["@sharlikran"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 0,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["lastScans"] = {
      [2] = 1713796433,
      [1] = 0,
    },
    ["@plant.mage"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597631795,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@admiralboofington"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597632892,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@elbowtoucher"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597632022,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@shurengyla"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597627080,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@oliverisadog"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597633946,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@gangburrito"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597632418,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@lazyboar"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597626781,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
    ["@poofus"] = {
      [21] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
      ["timeJoined"] = 1597633536,
      [22] = {
        [1] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [2] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [3] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [4] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [5] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [6] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [7] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
        [8] = {
          ["timeLast"] = 0,
          ["last"] = 0,
          ["total"] = 0,
          ["timeFirst"] = 0,
        },
      },
    },
  }
}